site_name: Crosstown Trail Cue Sheets
site_favicon: https://crosstowntrail.org/wp-content/uploads/2019/04/cropped-crosstowntraillogo-1-32x32.png
google_analytics: ['UA-140052176-1', 'crosstowntrail.org']
theme: 
   name: readthedocs
   highlightjs: false
docs_dir: cue-sheets